# Site settings
title: The Discord Wiki
email: email@this-is-a.website
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://discordia.me" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
